export const ROUTES = {
  LANDING: '/',
  ROOM_TIMER: '/roomTimer',
  ROOM_START: '/roomStart',
  ROOM_CALENDAR: '/roomCalendar',
  INVITE: '/invite',
  LOGIN: '/login',
  LOGIN_NICKNAME: '/login/nickname',
  CURRENT: '/current',
  ADD_TIME: '/addTime',
  RESULT: '/result',
  AUTH: '/auth',
  ERROR: '/error',
  PRIVACY: '/privacy',
};
