name: Check PR title

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

jobs:
  main:
    name: Check PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            hotfix
            refactor
            docs
            style
            design
            chore
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
